Name: Bou Haidara

Email: bhaidara@uncc.edu

## Matrices

For this lab, you'll be using numpy arrays to design functions that will perform matrix addition and math. If you need to review how Matrix addition and multiplication work, review the following links:

- [Multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication)
- [Addition](https://en.wikipedia.org/wiki/Matrix_addition)

##### A couple of notes:
- You should have two functions, one for addition, one for multiplication
- These functions should take two parameters, each one being a 2 Dimensional numpy array. It should return a numpy array.
- I am testing you on your ability to create the necessary loops, the arrays themselves, and your ability to use indexing and splicing in the context of a numpy array. You should not use any of the built in numpy methods to shortcut this process.
- Show your results. Let us see your test cases and what each produced.

Extra Credit opportunity: Bonus points can be earned for included the checks that would determine if addition or multiplication is allowed based on the dimensions of each array.

In [2]:
#you have to import numpy and you can replace it to a shorter name when doing these types of problems
import numpy as np

In [3]:
#the 2 arrays located below are 2 dimentional arrays
#the varaible name that is = "np.array" referes to the np library and the [array of numbers]
arr1 = np.array([[1,1],[1,1],[1,1]])
arr2 = np.array([[2,1],[5,7],[2,9]])

#The function to add the two arrays located above
def arrAdd(arr1,arr2):
    #Using a for loop that will loop throgh the arrary of i and add each number based on the cooesponding number
    for i in range(3):
        total=arr1[i]+arr2[i]
        print(total)
        
print(arrAdd(arr1,arr2))

[3 2]
[6 8]
[ 3 10]
None


In [4]:
#just to check if the answer is correct
np.add(arr1,arr2)

array([[ 3,  2],
       [ 6,  8],
       [ 3, 10]])

In [5]:
#This was a test to see if the function would work 
#the arrays for the arguments above have to be compatiable to be multiplied or line up the dimentions  
arr3 = np.array([[1,4,-2],[3,5,-6], [5,9,-1]]) #this is a 2 by 3 array
arr4 = np.array([[5,2,8],[3,6,4],[-2,9,7]]) #this is a 2 by 3 array


def arrMul(arr3,arr4):
#Using a for loop that will loop throgh the arrary of i and add each number based on the cooesponding number    
    for i in range(3):
        total2=arr3[i]*arr4[i]
        print(total2)
        
print(arrMul(arr3,arr4))

[  5   8 -16]
[  9  30 -24]
[-10  81  -7]
None


In [6]:
#just to check if the function above worked
np.dot(arr3,arr4)

array([[ 21,   8,  10],
       [ 42, -18,   2],
       [ 54,  55,  69]])

In [11]:
#https://www.youtube.com/watch?v=erdi5mtYSEQ&t=359s I used this video to understand the arrays multiplication
#rXc
arr5 = np.array([[1,4],[2,4]])#this is a 1 by 1 array
arr6 = np.array([[5,2],[7,1]])#this is a 1 by 1 array
#the arrays for the arguments above have to be compatiable to be multiplied or line up the dimentions
#the numbers have to be multiplied and then added together (row by column)

#print(arr5)
#print(arr6)
# I wanted to see if the numbers have to be multiplied and then added together (row by column)
#print(((sum(arr5[0,0] * arr6[0,0]))))

#the function takes the 2 arguments
def arrMult(arr5,arr6):
    #created an empty array to add the new intergers into
    total = []
    #the function goes through a for loop to loop through the first number in arr5 beacuse 
    for a in range(arr5[0]):
        #the function goes through another for loop through in the second arr6
        for b in range(arr6[0]):
            #after looping through the they are supposed to multiply and add the integers into the empty array
                total[i,j] += (arr5[i,x]) * (arr6[x,j])
                
    return total

print(arrMult(arr5,arr6))

TypeError: only integer scalar arrays can be converted to a scalar index

In [12]:
#just to check if the function above worked
np.dot(arr5,arr6)

array([[33,  6],
       [38,  8]])