Subtract the 1D Array *arr2* from the 2D array *arr1*, such that each item of *arr2* subtracts from respective row of *arr1*

Ex

arr1 = `[[x1, x2 , x3], [y1, y2, y3], [z1,z2,z3]]`

arr2 = `[x,y,z]`

Result `[ [ x1-x, x2-x, x3-x],` etc

In [1]:
import numpy as np
arr1 = np.arange(9).reshape(3,3)
                        #column , row for the reshape
arr2 = np.arange(3)
print(arr1)
print(arr2)

#arr1 - arr2

for i in range(3):
    arr = arr1[i]-arr2[i]
    print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[0 1 2]
[2 3 4]
[4 5 6]


Given a 1D Array, find the local maxima (numbers surrounded by 2 smaller numbers)

In [2]:
arr3 = np.array([1,5,2,4,0])
#print(arr3.shape[0]-2)
for i in range(1,len(arr3)-1):
    if arr3[i] > arr3[i-1] and arr3[i] > arr3[i+1]:
        print(arr3[i])

5
4


Given two n x m Arrays, compute the average of elements in matching subarrays

Ex

arr1      
`[[1,1],[2,2],[3,3]]`

arr2      
`[[1,1],[2,2],[3,3]]`

result:
`[1,2,3]`



In [6]:
#row x column multi row x column. the 2 in the middle have to be the same
a1 = np.array([[1,1],[2,2],[3,3]])
a2 = np.array([[1,1],[2,2],[3,3]])
a3 = np.zeros(3)
((sum(a1[0]) + sum(a2[0])) / (len(a1[0])*2))

1.0